### ISSUE TITLE
Werkt deze link?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Sascha-davidson/the-client-case#1]
Hou rekening met hoofdletters.

https://github.com/Sascha-davidson/the-client-case/blob/709f5c9058a10d2e76a26f22abd79b0beefb12b7/index.html#L115

**Comment by Sascha-Davidson** [comment]
Deze link werkt werkt wel local maar niet als ik het push naar github. Dit is nog iets waar ik op moet leten.
