### ISSUE TITLE
Hoe wordt dit voorgelezen?

### ISSUE THREAD

**Issue by KrijnHoetmer** [Sascha-davidson/the-client-case#2]
Heb je dit getest? Is het `alt` attribuut hier zinvol? Misschien heb je iets aan bijvoorbeeld https://www.w3.org/WAI/tutorials/images/decision-tree/, maar er zijn een hoop meer pagina's met uitleg over `alt` attributen.

https://github.com/Sascha-davidson/the-client-case/blob/709f5c9058a10d2e76a26f22abd79b0beefb12b7/index.html#L115-L118

**Comment by Sascha-Davidson** [comment]
Het word voor gelezen als "kennisbank kennisbank". Dit is nu aangepast.
